const List<String> attivitaSvolte = <String>[
  "Accettazione",
  "Amministratore",
  "Assistente educatore",
  "Assistente sociale",
  "Coordinatore",
  "Coordinatrice pedagogica",
  "Direttore sanitario",
  "Educatore professionale",
  "Fisioterapista",
  "Infermiere",
  "Logopedista",
  "Manutentore",
  "Massofisioterapista",
  "Medico",
  "Musicoterapista 1",
  "Musicoterapista 2",
  "OSS",
  "Psicologa dell'età evolutiva",
  "Psicomotricista",
  "Psicomotricista 1",
  "Psicomotricista 2",
  "Resp. della comunicazione",
  "Tecnico Informatico",
];

const List<String> sesso = <String>["maschio", "femmina"];

const statoCivile = <String>[
  "Coniugata/o",
  "Convivente/partner stabile",
  "Divorziata/o",
  "Non dichiarato",
  "Non risposta",
  "Nubile/Celibe",
  "Religiosa/o",
  "Separata/o",
  "Vedova/o",
];

const istruzione = <String>[
  "Diploma media superiore",
  "Diploma univers./Laurea Breve",
  "Laurea/Laurea Magistrale",
  "Licenza elementare",
  "Licenza Media",
  "Nessun titolo",
  "Non dichiarato",
  "Scuola professionale",
];

const professione = <String>[
  "Agente di commercio",
  "Agricoltore",
  "Allevatore",
  "Altro",
  "Altro lavoratore dipendente",
  "Anestesista",
  "Apprendista",
  "Architetto",
  "Assicuratore",
  "Assistente domiciliare",
  "Assistente sanitario",
  "Assistente sociale",
  "Ausiliario sociosanitario",
  "Autista",
  "Avvocato",
  "Barbiere",
  "Barista",
  "Bidello",
  "Biologo",
  "Cameriere/a",
  "Camionista",
  "Capo operaio",
  "operaio",
  "bracciante",
  "Carabiniere",
  "Casalinga",
  "Cassiere",
  "commercialista",
  "Commerciante",
  "Commesso",
  "Cuoco",
  "Dentista",
  "Dirigente",
  "Disoccupato",
  "Educatore Professionale",
  "Elettricista",
  "Esercito",
  "Falegname",
  "familiare coadiuvante",
  "Fornaio",
  "Geometra",
  "Governante",
  "Grafico",
  "Guardia Forestale",
  "Guardia giurata",
  "Idraulico",
  "Imbianchino",
  "Impiegata/o",
  "imprenditore",
  "Imprenditore",
  "in cerca di prima occupazione",
  "Infermiere/a",
  "Ingegnere",
  "Insegnante",
  "invalido",
  "lavoratore a domicilio per conto di imprese",
  "lavoratore in proprio",
  "libero professionista",
  "Logopedista",
  "Macellaio",
  "Magazziniere",
  "Maresciallo polizia",
  "Meccanico",
  "Medico",
  "Metereologo",
  "militare di carriera",
  "Minatore",
  "Muratore",
  "Nessuna",
  "Non risposta",
  "Operaia/o",
  "Ostetrica",
  "Parrucchiere",
  "Pensionato",
  "Poliziotto",
  "Professore universitario",
  "Programmatore",
  "Psicologo/a",
  "quadro direttivo",
  "Ragioniere",
  "Religioso",
  "Sacerdote",
  "Sarta",
  "Segretario",
  "studente",
  "Terapista riabilitazione",
  "Ufficiale aereonautica",
  "Ufficiale Aeronautica",
  "Ufficiale Esercito",
  "Veterinario",
  "Vigile urbano",
];

const condizioneProfessionale = <String>[
  "Altro",
  "Disoccupato",
  "Invalido 100%",
  "Non occupato",
  "Occupato",
  "Pensionato",
  "Studente",
];

// ignore: constant_identifier_names
const ASLdiAppartenenza = <String>[
  "FOL",
  "MVT",
  "NARNI-AMELIA",
  "PG",
  "TR",
  "TRAS",
  "SPOLETO",
];

const cittadinanza = <String>[
  "Italiana",
  "Albania",
  "Algeria",
  "Americana",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antartide",
  "Antigua e Barbuda",
  "Antille Olandesi",
  "Apolide",
  "Arabia Saudita",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria...",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belgio",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bielorussia",
  "Bolivia",
  "Bosnia Erzegovina",
  "Botswana",
  "Brasile",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambogia",
  "Camerun",
  "Canada",
  "Capo Verde",
  "Ciad",
  "Cile",
  "Cina",
  "Cipro",
  "Citta del Vaticano",
  "Colombia",
  "Comore",
  "Corea del Nord",
  "Corea del Sud",
  "Costa d'Avorio",
  "Costa Rica",
  "Croazia",
  "Cuba",
  "Danimarca",
  "Dominica",
  "Ecuador",
  "Egitto",
  "Eire",
  "El Salvador",
  "Emirati Arabi Uniti",
  "Eritrea",
  "Estonia",
  "Etiopia",
  "Federazione Russa",
  "Fiji",
  "Filippine",
  "Finlandia",
  "Francese",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germania",
  "Ghana",
  "Giamaica",
  "Giappone",
  "Gibilterra",
  "Gibuti",
  "Giordania",
  "Grecia",
  "Grenada",
  "Groenlandia",
  "Guadalupa",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea Equatoriale",
  "Guinea-Bissau",
  "Guyana",
  "Guyana Francese",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Islanda",
  "Isola di Bouvet",
  "Isola di Man",
  "Isola di Natale",
  "Isola Heard e Isole McDonald",
  "Isola Norfolk",
  "Isole Cayman",
  "Isole Cocos",
  "Isole Cook",
  "Isole Falkland",
  "Isole Faroe",
  "Isole Marianne Settentrionali",
  "Isole Marshall",
  "Isole Minori degli Stati Uniti d'America",
  "Isole Solomon",
  "Isole Turks e Caicos",
  "Isole Vergini Americane",
  "Isole Vergini Britanniche",
  "Israele",
  "Italiana",
  "Kazakhistan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Laos",
  "Lesotho",
  "Lettonia",
  "Libano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Lussemburgo",
  "Macao",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Maldive",
  "Malesia",
  "Mali",
  "Malta",
  "Marocco",
  "Martinica",
  "Mauritania",
  "Maurizius",
  "Mayotte",
  "Messico",
  "Moldavia",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Mozambico",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norvegia",
  "Nuova Caledonia",
  "Nuova Zelanda",
  "Oman",
  "Paesi Bassi",
  "Pakistan",
  "Palau",
  "PanamÃ¡",
  "Papua Nuova Guinea",
  "Paraguay",
  "Peru",
  "Pitcairn",
  "Polinesia Francese",
  "Polonia",
  "Porto Rico",
  "Portogallo",
  "Qatar",
  "Regno Unito",
  "Repubblica Ceca",
  "Repubblica Centroafricana",
  "Repubblica del Congo",
  "Repubblica Democratica del Congo",
  "Repubblica Dominicana",
  "Reunion",
  "Romania",
  "Ruanda",
  "Sahara Occidentale",
  "Saint Kitts e Nevis",
  "Saint Pierre e Miquelon",
  "Saint Vincent e Grenadine",
  "Samoa",
  "Samoa Americane",
  "San Marino",
  "Santa Lucia",
  "Sant'Elena",
  "Sao Tome e Principe",
  "SCONOSCIUTO",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Siria",
  "Slovacchia",
  "Slovenia",
  "Somalia",
  "Spagna",
  "Sri Lanka",
  "Stati Federati della Micronesia",
  "Sud Africa",
  "Sud Georgia e Isole Sandwich",
  "Sudan",
  "Suriname",
  "Svalbard e Jan Mayen",
  "Svezia",
  "Svizzera",
  "Swaziland",
  "Tagikistan",
  "Tailandia",
  "Taiwan",
  "Tanzania",
  "Territori Britannici dell'Oceano Indiano",
  "Territori Francesi del Sud",
  "Territori Palestinesi Occupati",
  "Timor Est",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad e Tobago",
  "Tunisia",
  "Turchia",
  "Turkmenistan",
  "Tuvalu",
  "Ucraina",
  "Uganda",
  "Ungheria",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Wallis e Futuna",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const List<String> provincia = <String>[
  "Agrigento",
  "Alessandria",
  "Ancona",
  "Aosta",
  "Arezzo",
  "Ascoli Piceno",
  "Asti",
  "Avellino",
  "Bari",
  "Barletta-Andria-Trani",
  "Belluno",
  "Benevento",
  "Bergamo",
  "Biella",
  "Bologna",
  "Bolzano",
  "Brescia",
  "Brindisi",
  "Cagliari",
  "Caltanissetta",
  "Campobasso",
  "Carbonia-Iglesias",
  "Caserta",
  "Catania",
  "Catanzaro",
  "Chieti",
  "Como",
  "Cosenza",
  "Cremona",
  "Crotone",
  "Cuneo",
  "Enna",
  "Fermo",
  "Ferrara",
  "Firenze",
  "Foggia",
  "Forlì-Cesena",
  "Frosinone",
  "Genova",
  "Gorizia",
  "Grosseto",
  "Imperia",
  "Isernia",
  "La Spezia",
  "L'Aquila",
  "Latina",
  "Lecce",
  "Lecco",
  "Livorno",
  "Lodi",
  "Lucca",
  "Macerata",
  "Mantova",
  "Massa-Carrara",
  "Matera",
  "Messina",
  "Milano",
  "Modena",
  "Monza e della Brianza",
  "Napoli",
  "Novara",
  "Nuoro",
  "Olbia-Tempio",
  "Oristano",
  "Padova",
  "Palermo",
  "Parma",
  "Pavia",
  "Perugia",
  "Pesaro e Urbino",
  "Pescara",
  "Piacenza",
  "Pisa",
  "Pistoia",
  "Pordenone",
  "Potenza",
  "Prato",
  "Ragusa",
  "Ravenna",
  "Reggio Calabria",
  "Reggio Emilia",
  "Rieti",
  "Rimini",
  "Roma",
  "Rovigo",
  "Salerno",
  "Medio Campidano",
  "Sassari",
  "Savona",
  "Siena",
  "Siracusa",
  "Sondrio",
  "Taranto",
  "Teramo",
  "Terni",
  "Torino",
  "Ogliastra",
  "Trapani",
  "Trento",
  "Treviso",
  "Trieste",
  "Udine",
  "Varese",
  "Venezia",
  "Verbano-Cusio-Ossola",
  "Vercelli",
  "Verona",
  "Vibo Valentia",
  "Vicenza",
  "Viterbo",
];

const String formSezOneExplatation = """
Questo test di valutazione musicale  iniziale rivolto a ragazzi con disabilità intellettiva permette di investigare tre macro aree relative al rapporto che l'uomo ha sviluppato con i suoni e la musica, offre la possibilità di "fotografare":

1) l' Età musicale cioè l' apprendimento/euridizione musicale dell'assistito.
Permette di definire l’età musicale dell'assistito e di fare una seguente comparazione con la usa età reale e l'età mentale diagnostica con test di valutazione.

2) il Mood (Modo di Essere) cioè il modo in cui l'assistito  interagisce nella relazione con il setting musicoterapico, il terapista e nella gestione dell’emotività.

3) la "Musicofilia" cioè il modo in cui l'assistito  percepisce la musica, come la elaborata e utilizza all'interno del suo percorso storico evolutivo e nella complessità della sua vita.

Tutto parte dall’idea che gli assistiti con pluri disabilità, sindromici e con disabilità intellettiva anche gravissima sviluppano una capacità di elaborazione e utilizzo del suono molto più elaborata di quanto possiamo immaginare.
Così, come cerchiamo di sviluppare apprendimenti tramite il supporto visivo o tattile, può essere fatto in modo significativo anche attraverso il suono. Questo è chiaro osservando i nostri assisiti che non possono spostarsi nello spazio (tetra paresi spastica, PCI ecc.), che non possono afferrare oggetti o anche se lo fanno (ritardo mentale, X fragile, autismo, sindrome di down ecc) non hanno un uso funzionale dell'oggetto,  uno uso che li portino a sviluppare schemi di apprendimento.
Bene, entrando in relazione, accogliendo  e osservando i nostri assisiti in un'esperienza sonoro-musicale è sempre più chiaro come questi sviluppino una specifica capacità di differenziare lo stimolo acustico che li porta:

- a distinguere i timbri delle voci (es. della madre o di un estraneo - affettività)
- ad avere gusti musicali specifici (cultura)
- a favorire un tipo di strumento al posto di un altro (forma, materiale costitutivo, colore, odore)
- a gradire maggiormente il suono prodotto da strumenti di legno o di metallo, a corde o a membrana (timbro-qualità)
- a gradire maggiormente esperienze ritmiche ad esperienze melodiche o viceversa

Stupisce la capacità che i nostri assistiti hanno, pur vivendo spesso in un mondo non-verbale, di intonare il centro tonale di un improvvisazione musicale tramite il vocalizzo e di improvvisare utilizzando altezze specifiche coerenti con lo sfondo armonico proposto e/o di cambiare atteggiamenti in relazione al suono somministrato.
Questa scheda ha la presunzione di affermare con certezza che ciò che “passa” da un punto di vista acustico rimane nella memoria e permette all'assistito con lieve, media e grave disabilità intellettiva  di sviluppare una serie di informazioni proto-comunicative significative che vengono impresse (forma, intensità e durata) negli eventi, diventando espressione di contenuti relazionali-affettivi.

Quindi, questa scheda nasce come strumento di Valutazione iniziale in ambito Musicoterapico. Le teorie di riferimento che fondano la (VMt-D) sono:

1) Età musicale: partendo dalla teoria della Music Learning Theory  vengono comparate le competenze musicali dell' assistito  in relazione agli stadi di Audition preparatoria fornendoci informazioni in merito "all’età musicale" del ragazzo/bambino in relazione alle competenze musicali. Ci permette così di comparare l'età musicale rilevata da questa scheda  con l'età mentale del ragazzo (rilevata con schede accreditate) e l'età reale del ragazzo. La  VMt-D ci indicherà in quale area musicale evolutiva  possiamo collocare il ragazzo/bambino (Acculturazione, Imitazione, Assimilazione) e andare a proporre attività musicali specifiche per farlo evolvere nel rapporto con il suo mondo acustico, sonoro-musicale e di conseguenza relazionale. (CFR - Introduzione alla Musica Learning Theory di E. Gordon di A.Sangiorgio)
Un' altra teorizzazione di riferimento  è quella sugli universali musicali rintracciati da F. Delalnde. Il semiologo francese ha analizzato gli atteggiamenti sonoro-musicali dei bambini, prima che intervengono  condizionamenti culturali. L'osservazione sistemica gli ha permesso di individuare le costanti nel comportamento musicale infantile che da Delalande vengono definite "condotte". In sintesi per Delalande la musica è un gioco senso-motorio, di movimenti e percezioni che innescano il piacere della reiterazione e il gioco di esercizio, un gioco simbolico, ovvero di investimento emotivo e simbolico del suono che diviene portatore di idee, affetti, miti, visioni; infine un gioco di regole, di combinazione dei suoni, secondo una sitassi interna".(CFR - Per una pedagogia dell'uomo musicale G. Mocchi).

2) Il Mood - “modo di essere”: è stato pensato all’interno dello studio dell’infant reserch, utilizzando i domini dei vari possibili stili di attaccamento: sicuro, evitante, resistente/ambivalente, disorganizzato/disorientato in relazione alla modalità in cui l'assistito entra in relazione con il setting, il terapista e nella gestione dell’emotività. Quindi, potremmo trovare l'assistito che, in relazione alla propria diagnosi funzionale della disabilità, esplora la stanza e gli strumenti musicali, cerca un contatto fisico con il valutatore, presenta un atteggiamento sereno, aperto ed organizzato per entrare in relazione e che ha un buon controllo dell'emotività...in questo caso ci troveremmo in una situazione in cui l'assistito ha un "Mood Sicuro"; all'opposto ci troveremo difronte ad un assistito con un "Mood Disorganizzato/disorientato". AGGIUGERE STERN TREVARTEN INTERSOGGETTIVITA'.

3) La Musicofilia:  cioè il modo in cui l'assistito  percepisce la musica, come la elaborata e utilizza all'interno del suo percorso storico evolutivo e nella complessità della sua vita... in sintesi: come viene esplicitata la passione per la musica da parte dei nostri assistiti. Tale termine viene preso in prestito citando l'omonimo testo di Oliver Sacks con cui ha  indagato "Il rapporto tra il cervello e gli organi uditivi, tra questi e le emozioni, la relazione tra eccitazione vitale o depressione ferale e musica, la capacità dell’organismo di autoriparare le proprie ferite neurologiche potenziando alcune abilità per compensare quelle carenti". Da qui la partecipazione ad un convegno il 7 novembre 2016 all'ospedale di Arezzo e l'intervento di Luccherino in cui spiegava le differenti condotte che possiamo assumere nei confronti di un' esperienza musicale. Così questa parte della scheda indagherà come l'assistito si pone nei confronti della musica vivendola in modo razionale o emotiva, ponendosi a fianco o dentro la musica, possiamo girare intorno alla musica, "assaggiandola" di tanto in tanto o porsi in relazione con essa.

I dati raccolti dall'Età musicale, il Mood e la Musicofilia verranno sintetizzati in tre grafici e ci permetteranno di avere una valutazione iniziale del nostro assistito che potrà essere comparata con una rivalutazione durante lo sviluppo del processo relazionale sonoro-musicale.

Di seguito vengono fornite alcune raccomandazioni riguardanti l'uso delle opzioni di risposta:

1 = “Mai”  è una risposta adeguata nel caso in cui la persona non faccia mai o non sia mai soggetta a quanto specificato nel contenuto dell’ item. Per esempio, per rispondere a "gira la testa, guarda verso la fonte sonora/musica", si dovrà marcare l'opzione "mai" se, durante l'osservazione, la persona non lo fa mai.

2 = “Qualche volta” è la risposta appropriata nel caso in cui la persona faccia o sia soggetta solo qualche volta (ma non nella maggior parte dei casi), a quanto specificato nell’item. Per esempio, per rispondere a "gira la testa, guarda verso la fonte sonora/musica", si dovrà marcare l'opzione "qualche volta" se la persona in questione lo fa 2 o 3 volte in un incontro di osservazione.

3 = “Frequentemente” è la risposta idonea nel caso in cui la persona faccia o sia frequentemente soggetta a quanto specificato nell’item, ossia nella maggior parte dei casi. Ad esempio, per rispondere a "gira la testa, guarda la fonte sonora/musica", si dovrà marcare l'opzione "frequentemente" se la persona in questione lo fa tra i 4 o i 6 volte durante l'incontro.

4 = “Sempre” è la miglior opzione nel caso in cui la persona faccia o sia sempre soggetta a quanto specificato nell’item. Ad esempio, per rispondere a "gira la testa, guarda la fonte sonora/musica", si dovrà marcare l'opzione "sempre" se la persona in questione lo fa  in modo coerente e tutte le volte (anche nel caso in cui ci sia qualche eccezione).

Lorenzo Capolsini - gennaio 2017 - Revisionato ottobre 2020

""";

const String formSezThreeExplatation = """
- L'assistito partecipa con poca consapevolezza dell'ambiente. (E. Gordon)
- E' la fase della ricerca di un piacere a livello gestuale, tattile e uditivo. (F. Delalande)
- Incontrare musicalmente l'assistito (Nordoff-Robbins)

L'assistito durante l'incontro di musicoterapia:

""";

const String formSezFourExplatation = """
- Partecipa con pensiero consapevole focalizzato primariamente sull'ambiente. (E. Gordon)
- E' la fase di un investimento simbolico dell'oggetto musicale messo in rapporto con un vissuto (esperienza del movimento, affetti) o con certi aspetti della cultura: miti, vita sociale. (F. Delalande)
- Evocare risposte musicali (Nordoff-Robbins)

L'assistito durante l'incontro di musicoterapia:
""";

const String formSezFiveExplatation = """
- Partecipa con pensiero consapevole focalizzato su se stesso. (E.Gordon)
- E' la fase  della soddisfazione intellettuale che risulta dal gioco di regole. (F. Delalande)
- Sviluppare abilità musicali, libertà espressività, rispondenza reciproca (Nordoff-Robbins)

L'assistito durante l'incontro di musicoterapia:
""";

const String formSezSixExplatation = """
Questa sessione indaga lo stile con cui la persona interagisce nella relazione con il setting, il terapista e la propria emotività. La domanda sottintesa è:

L'assistito durante l'incontro di musicoterapia:
""";

const String formSezSevenExplatation = """
Questa sessione indaga in che modo l'assistio si rapporta con l'esperienza acustica, sonoro-musicale. Ci permette di capire come l'assistito percepisce la musica, come la elaborata e utilizza all'interno del suo percorso storico evolutivo e in relazione con l'altro da sé.  

Di seguito vengono fornite alcune raccomandazioni riguardanti l'uso delle opzioni di risposta:

1 = “assente”  è una risposta adeguata nel caso in cui la persona non faccia mai o non sia mai soggetta a quanto specificato nel contenuto dell’ item. Per esempio, per rispondere a "Mimica", si dovrà marcare l'opzione "assente" se, durante l'osservazione, la persona non lo fa mai.

2 = “Qualche volta” è la risposta appropriata nel caso in cui la persona faccia o sia soggetta solo qualche volta (ma non nella maggior parte dei casi), a quanto specificato nell’item. Per esempio, per rispondere a "Mimica", si dovrà marcare l'opzione "qualche volta" se la persona in questione lo fa 2 o 3 volte in un incontro di osservazione.

3 = “Frequentemente” è la risposta idonea nel caso in cui la persona faccia o sia frequentemente soggetta a quanto specificato nell’item, ossia nella maggior parte dei casi. Ad esempio, per rispondere a "Mimica", si dovrà marcare l'opzione "frequentemente" se la persona in questione lo fa tra i 4 o i 6 volte durante l'incontro.

4 = “Sempre” è la miglior opzione nel caso in cui la persona faccia o sia sempre soggetta a quanto specificato nell’item. Ad esempio, per rispondere a "Mimica", si dovrà marcare l'opzione "sempre" se la persona in questione lo fa  in modo coerente e tutte le volte (anche nel caso in cui ci sia qualche eccezione).


Come valuta la persona difronte ad un'esperienza musicale (attiva o recettiva) esperita in coppia in relazione alla:
""";
